openapi: 3.0.0
info:
  title: Meteostation API
  description: REST API for Meteostation project
  version: "1.0.0"

paths:

  # ----------------- LOCATION -----------------
  /locations:
    get:
      summary: Get all locations
      responses:
        '200':
          description: List of locations
    post:
      summary: Create a new location
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                location:
                  type: string
                stat:
                  type: string
      responses:
        '201':
          description: Location created

  /locations/{location_id}:
    get:
      summary: Get location by ID
      parameters:
        - name: location_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Location found
    put:
      summary: Update location by ID
      parameters:
        - name: location_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                location:
                  type: string
                stat:
                  type: string
      responses:
        '200':
          description: Location updated
    delete:
      summary: Delete location by ID
      parameters:
        - name: location_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Location deleted

  # ----------------- GENDER -----------------
  /genders:
    get:
      summary: Get all genders
      responses:
        '200':
          description: List of genders
    post:
      summary: Create a new gender
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
      responses:
        '201':
          description: Gender created

  /genders/{gender_id}:
    get:
      summary: Get gender by ID
      parameters:
        - name: gender_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Gender found
    put:
      summary: Update gender by ID
      parameters:
        - name: gender_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
      responses:
        '200':
          description: Gender updated
    delete:
      summary: Delete gender by ID
      parameters:
        - name: gender_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Gender deleted

  # ----------------- INTERVAL_TYPE -----------------
  /interval_types:
    get:
      summary: Get all interval types
      responses:
        '200':
          description: List of interval types
    post:
      summary: Create a new interval type
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
      responses:
        '201':
          description: Interval type created

  /interval_types/{interval_id}:
    get:
      summary: Get interval type by ID
      parameters:
        - name: interval_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Interval type found
    put:
      summary: Update interval type by ID
      parameters:
        - name: interval_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
      responses:
        '200':
          description: Interval type updated
    delete:
      summary: Delete interval type by ID
      parameters:
        - name: interval_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Interval type deleted

  # ----------------- TYPE_WORK -----------------
  /type_works:
    get:
      summary: Get all type works
      responses:
        '200':
          description: List of type works
    post:
      summary: Create a new type work
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
      responses:
        '201':
          description: Type work created

  /type_works/{type_work_id}:
    get:
      summary: Get type work by ID
      parameters:
        - name: type_work_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Type work found
    put:
      summary: Update type work by ID
      parameters:
        - name: type_work_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
      responses:
        '200':
          description: Type work updated
    delete:
      summary: Delete type work by ID
      parameters:
        - name: type_work_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Type work deleted
